[package]
name = "dices"
version = "0.1.0"
authors = ["Anders Jensen <anders.c.jensen@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rayon = "1.7"
bytecount = "0.6.2"
